build-job:
  tags:
    - Macos
  stage: build
  script:
    - echo "Hello, world"
    - pwd
    - terraform init
    - terraform plan
    - terraform aplly -auto-approve
    - terraform destroy -auto-approve