build-job:
  tags:
    - Testing
  stage: build
  script:
    - echo "Hello, world"
    - pwd


build-job1:
  tags:
    - Testing
  stage: build
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
    #- terraform destroy --auto-approve
  when: manual