build-job:
  tags:
    - Macos
  stage: build
  script:
    - echo "Hello, world"
    - pwd


build-job1:
  tags:
    - Macos
  stage: build
  script:
    - terraform init
    - terraform apply --auto-approve
    - terraform destroy --auto-approve
  when: manual