build-job:
  tags:
    - Macos
  stage: build
  script:
    - echo "Hello, world"
    - pwd
    - terraform init

build-job1:
  tags:
    - Macos
  stage: build
  script:
    - terraform apply --auto-approve
    - terraform destroy --auto-approve
  when: manual

build-job2:
  tags:
    - Macos
  stage: build
  script:
    - terraform apply --auto-approve
    - terraform destroy --auto-approve
  when: manual